 # Site
repository: kyle-and-error/kyle-and-error.github.io
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Kyle Cho
title: Web App Developer and Amateur Game Designer
email: kylescho99@gmail.com
website: www.kyle-and-error.github.io

# Dark Mode (true/false/never)
darkmode: true

# Social links
twitter_username: kyle_and_3rror
github_username:  kyle-and-error
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: kyle_and_error
linkedin_username: kyle-cho-2000
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
- title: torre.com
  icon: fas fa-globe
  url: https://torre.co/en/kcho
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name is Kyle and I'm a Computer Science student at Elon University. I'm extremely interested in the creative potential of programming in both games and applications. I'm proficient in GameMaker Studio 2, mySQL, and a number of Object Oriented Programming languages. I am a Le Wagon Alumni (Batch #269), and plan to graduate from Elon University in 2023.

content:
  
  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Elon University
        caption: 2018 - Current
        sub_title: BSc Computer Science
        quote: >
          Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        description: | # this will include new lines to allow paragraphs
      
  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Freelance Tutor
        caption: March 2018 - Present
        description: | # this will include new lines to allow paragraphs
            I have tutored many people in programming languages like Java, frameworks like Ruby on Rails, or more general subjects for high schoolers to prepare them for the SAT or ACT. 
      - layout: left
        title: Assistant Swim Coach
        sub_title: Carderock Springs Swim and Tennis Club
        caption: June 2017 - May 2018
        description: | # this will include new lines to allow paragraphs
            I have tutored many people in programming languages like Java, frameworks like Ruby on Rails, or more general subjects for high schoolers to prepare them for the SAT or ACT. 


  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Untitled RPG
        # link_text: Project Website
        # additional_links:
          # - title:  sproogen/modern-resume-theme
            # icon: fab fa-github
            # url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        # quote: >
          # This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
        description: | # this will include new lines to allow paragraphs
          This game is currently being developed in Game Maker Studio 2

  - title: Practical Skills and Certifications
    layout: text
    content: |
      - Codecademy Certifications
        - Java
        - JavaScript
        - Ruby
        - HTML
        - CSS
        - mySQL
      - LeWagon Certification
        - Full-Stack Web Development including skills such as
          - Ruby on Rails
          - HTML
          - CSS
          - Relational Databases and Database Management
      - Extremely Proficient in
        - Python 3
        - GameMaker Studio 2
        - Git, Bash and ZSH/Oh My ZSH

      Please note that I consider myself to be extremely proficient in any skill I am certified in (by any organization).

  - title: Soft Skills
    layout: text
    content: |
      - Detail Oriented
      - Good verbal and written communicator
      - Problem solver
      - Adaptable and flexible
          - Creative
      - Teamwork
          - Open to criticism/Good listener and learner
          - Good teacher to a range of ages
      - Research Skills
          - Knows best sources for informations
          - Keeps up to date for relevant communities and forums

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in game and web development, some of my other interests and hobbies are:
      - Ultimate Frisbee
      - Gaming
      - Working out

      Look at this cool image  
      ![Trees](images/landscape-trees.jpg "Trees")

  - layout: list
    title: Don't Like This Resume?
    content: 
      - layout: left
        title: PDF version of my resume
        link: https://docs.google.com/document/d/1lc9mgM9j3jNg2Q_Ji1f2M5pv8ogBTKN1z17wE983dck/export?format=pdf
        link_text: Download
        description: |
          <iframe src="https://docs.google.com/document/d/e/2PACX-1vQH3ovg1l8sydoNXORGwIpihyHEzGHIK4T4h0kSQFEN_3Ih4M7vVPQE2kXPzE0U-uxhjMK9rnMS6z9b/pub?embedded=true"></iframe>

# Footer
footer_show_references: true
references_title: 2408889685 References on request

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag