 # Site
repository: kyle-and-error/kyle-and-error.github.io
favicon: files/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Kyle Cho
pronouns: He/they
title: Web App Developer and Amateur Game Designer
email: kylescho99@gmail.com
email2: kcho@elon.edu
phone: +1(240) 888-9685
website: www.kyle-and-error.github.io

# Dark Mode (true/false/never)
darkmode: true

# Social links
twitter_username: kyle_and_3rror
github_username:  kyle-and-error
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: kyle_and_error
linkedin_username: kyle-cho-2000
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
- title: torre.com
  icon: fas fa-globe
  url: https://torre.co/en/kcho
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: files/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name is Kyle and I’m a Computer Science student at Elon University and a Le Wagon Alumni (Batch #269). I plan to graduate from Elon in 2023. I'm extremely interested in the creative potential of programming in both games and applications. I’m proficient in various programming languages, including Python, GameMakerStudio, and Ruby. I am a freelance tutor (Hire me!) and former swim coach. I am currently looking for employment!
content:

  - title: Education # Title for the section

  - title: Experience

# - title: skills
  
  - title: Projects

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in game and web development, some of my other interests and hobbies are:
      - Ultimate Frisbee
      - Gaming
      - Working out

    # Look at this cool image  
    # ![Trees](files/landscape-trees.jpg "Trees")


#  - layout: list
#    title: Don't Like This Resume?
#    content: 
#      - layout: left
#        link: https://docs.google.com/document/d/1lc9mgM9j3jNg2Q_Ji1f2M5pv8ogBTKN1z17wE983dck/export?format=pdf
#        link_text: Download
#        additional_links:
#        - title:  resume-view
#          icon: fab fa-google-drive
#          url: https://docs.google.com/document/d/1lc9mgM9j3jNg2Q_Ji1f2M5pv8ogBTKN1z17wE983dck/edit?usp=sharing
#        iframe: https://docs.google.com/document/d/e/2PACX-1vQH3ovg1l8sydoNXORGwIpihyHEzGHIK4T4h0kSQFEN_3Ih4M7vVPQE2kXPzE0U-uxhjMK9rnMS6z9b/pub?embedded=true

# Footer 
footer_show_references: true
references_title: References on request
footer_notes: | # Add some additional text to your footer
  This site was built using Jekyll and Liquid, based on Sproogden's !(modern-resume-theme)[github.com/sproogen/modern-resume-theme "modern-resume-theme"] with heavy personalization.


sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag